import Head from "next/head";
import Image from "next/image";

import styles from "../styles/Home.module.css";
import { useRef, useState } from "react";
import Header from "../components/layout/header";

import { LogoIcon } from "../components/logo";
import { RightArrowIcon } from "../components/icons/RightArrowIcon";

import image1 from "../public/blue-room.jpg";
import image2 from "../public/grey-room.jpg";
import image3 from "../public/livingroom.jpg";
import image4 from "../public/lush-room.jpg";
import image5 from "../public/plant-room.jpg";
import image6 from "../public/mirror-room.jpg";

import CTA from "../components/cta";
import Card from "../components/card";
import FadeIn from "../components/fade-in";

import { getRecentPosts } from "../lib/posts";
import RecentPosts from "../components/recent-posts";
import Footer from "../components/layout/footer";
import { Dialog } from "@headlessui/react";
import FocusShowcase from "../components/focus-showcase";

const constants = [
  {
    image: image1,
    heading: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    summary:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consequuntur exercitationem dignissimos, non modi ratione repudiandae praesentium iste alias ullam dolores quia! Sequi non est dolorum quasi eum debitis aliquid cumque?",
    category: "Category",
  },
  {
    image: image2,
    heading: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    summary:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consequuntur exercitationem dignissimos, non modi ratione repudiandae praesentium iste alias ullam dolores quia! Sequi non est dolorum quasi eum debitis aliquid cumque?",
    category: "Category",
  },
  {
    image: image3,
    heading: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    summary:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consequuntur exercitationem dignissimos, non modi ratione repudiandae praesentium iste alias ullam dolores quia! Sequi non est dolorum quasi eum debitis aliquid cumque?",
    category: "Category",
  },
  {
    image: image4,
    heading: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    summary:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consequuntur exercitationem dignissimos, non modi ratione repudiandae praesentium iste alias ullam dolores quia! Sequi non est dolorum quasi eum debitis aliquid cumque?",
    category: "Category",
  },
  {
    image: image5,
    heading: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    summary:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consequuntur exercitationem dignissimos, non modi ratione repudiandae praesentium iste alias ullam dolores quia! Sequi non est dolorum quasi eum debitis aliquid cumque?",
    category: "Category",
  },
  {
    image: image6,
    heading: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    summary:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consequuntur exercitationem dignissimos, non modi ratione repudiandae praesentium iste alias ullam dolores quia! Sequi non est dolorum quasi eum debitis aliquid cumque?",
    category: "Category",
  },
];

export default function Home({ recentPosts }) {
  const [videoModalOpen, setVideoModelOpen] = useState(false);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="relative h-screen">
        <video
          autoPlay
          playsInline
          loop
          muted
          className="fixed right-0 w-full bottom-0 min-h-screen object-cover"
        >
          <source src="video2.mp4" type="video/mp4" />
        </video>
        <div className="fixed inset-0 bg-black opacity-40"></div>
        <div className="fixed inset-0 text-white">
          <div className="max-w-[1920px] max-h-15 mx-auto flex flex-col h-full justify-between">
            <Header />
            <FadeIn
              transition="transition-[transform,opacity] duration-1000 delay-500"
              enter="translate-y-0 opacity-1"
              leave="translate-y-5 opacity-0"
              className="absolute top-1/2 -translate-y-1/2 grid auto-rows-min grid-cols-12 p-10"
            >
              <h1 className="col-span-full text-4xl sm:text-5xl md:text-6xl lg:text-6xl xl:text-7xl 2xl:text-8xl pb-5 lg:pb-10 ">
                Lorem, ipsum dolor
              </h1>
              <p className="col-span-full lg:col-start-2 lg:col-end-6 text-base  sm:text-lg md:text-xl  lg:text-xl xl:text-2xl 2xl:text-3xl">
                Verdien av et rom defineres ikke av vegger, gulv eller tak. Den
                defineres av opplevelsen du får av å være der. Vi utvikler,
                designer og bygger taktile, visuelle og emosjonelle miljøer der
                folk lever, møtes eller jobber. Monn skaper inspirerende og
                minneverdige inntrykk. Fra innsiden og ut.
              </p>
              <button
                onClick={() => setVideoModelOpen(true)}
                className="pt-8 col-span-full lg:hidden flex gap-4 sm:text-lg md:text-xl lg:text-2xl xl:text-3xl 2xl:text-4xl "
              >
                <RightArrowIcon className="shrink-0 text-3xl"></RightArrowIcon>
                <p>Brand film</p>
              </button>
            </FadeIn>
            <div className="relative bottom-0 grid grid-cols-12 px-10 pb-24 ">
              <button
                onClick={() => {
                  console.log("CLICK");
                  setVideoModelOpen(true);
                }}
                className="invisible lg:visible flex gap-8 sm:text-lg md:text-xl lg:text-2xl xl:text-3xl 2xl:text-4xl justify-self-start items-end col-span-5"
              >
                <RightArrowIcon className="shrink-0"></RightArrowIcon>
                <p>Brand film</p>
              </button>
              <LogoIcon className="text-[20vmin] col-end-12"></LogoIcon>
            </div>
            <Dialog
              className={"fixed inset-0 flex justify-center items-center"}
              open={videoModalOpen}
              onClose={() => setVideoModelOpen(false)}
            >
              <div className="absolute h-screen w-screen bg-black opacity-80"></div>
              <Dialog.Panel className="bg-blue-200 w-[80vmax] relative m-10">
                <video playsInline controls>
                  <source src="video2.mp4" type="video/mp4" />
                </video>
              </Dialog.Panel>
            </Dialog>
          </div>
        </div>
      </div>

      <CTA />

      <div className="relative min-h-screen bg-[#ECECEA] flex justify-center">
        <div className="max-w-[1920px] w-screen flex flex-col relative gap-10 mt-10 lg:gap-12 lg:px-14 lg:py-28 ">
          <RecentPosts posts={recentPosts}></RecentPosts>
          <FadeIn>
            <FocusShowcase />
          </FadeIn>
          <LogoIcon className="text-[30vmin] col-end-12 self-end mr-10 mb-10"></LogoIcon>
        </div>
      </div>

      <Footer />
    </>
  );
}

export async function getStaticProps() {
  const recentPosts = await getRecentPosts();

  return {
    props: {
      recentPosts,
    },
  };
}
